# Generated by Django 5.1.8 on 2026-06-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_type_supportticketmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticketmessage',
            name='image',
        ),
        migrations.AlterField(
            model_name='supportticketmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SupportTicketMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_tickets/message_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.supportticketmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
