# Generated by Django 5.1.8 on 2026-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_supportticketmessage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticketmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
