# Generated by Django 5.1.8 on 2026-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_supportticketmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('promo', 'Promotional Offer'), ('price_change', 'Price Change'), ('leftover_pack', 'Leftover Pack Available'), ('ticket_reply', 'Support Ticket Reply'), ('admin_alert', 'Admin Alert'), ('out_of_stock', 'Out of Stock Alert'), ('wholesale_pending', 'Wholesale Pending Approval')], max_length=20),
        ),
    ]
