# Generated by Django 5.1.8 on 2026-06-10 04:54

import uuid
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stats', models.JSONField(default=website.models.AboutPageContent.default_stats, help_text='List of stats objects {value, label}')),
                ('values', models.JSONField(default=website.models.AboutPageContent.default_values, help_text='List of value objects {icon_name, title, body}')),
                ('milestones', models.JSONField(default=website.models.AboutPageContent.default_milestones, help_text='List of timeline milestone objects {year, event}')),
                ('farm_partners', models.JSONField(default=website.models.AboutPageContent.default_farm_partners, help_text='List of farm partners {name, region, specialty}')),
                ('team', models.JSONField(default=website.models.AboutPageContent.default_team, help_text='List of team members {name, role, initials, origin}')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
