# Generated by Django 5.1.8 on 2026-06-10 05:01

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hero_section',
            field=models.JSONField(default=website.models.AboutPageContent.default_hero, help_text='Hero section data {badge, title, image_url}'),
        ),
    ]
