# Generated by Django 5.1.8 on 2026-06-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutpagecontent_hero_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload image for hero section (overrides image_url in JSON)', null=True, upload_to='about/'),
        ),
    ]
