# Generated by Django 5.1.8 on 2026-06-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_aboutpagecontent_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_section', models.JSONField(blank=True, default=dict)),
                ('how_it_works', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('leftover_banner', models.JSONField(blank=True, default=dict)),
                ('hero_image_desktop', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('hero_image_mobile', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('leftover_banner_image', models.ImageField(blank=True, null=True, upload_to='homepage/leftover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
