# Generated by Django 5.1.8 on 2026-06-10 08:20

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_homepagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_section',
            field=models.JSONField(blank=True, default=website.models.HomePageContent.default_hero),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='how_it_works',
            field=models.JSONField(blank=True, default=website.models.HomePageContent.default_how_it_works),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='leftover_banner',
            field=models.JSONField(blank=True, default=website.models.HomePageContent.default_leftover_banner),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='steps',
            field=models.JSONField(blank=True, default=website.models.HomePageContent.default_steps),
        ),
    ]
