# Generated by Django 5.1.8 on 2026-06-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_coupon_code_alter_coupon_discount_amount_and_more'),
        ('products', '0007_alter_product_shipping_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('DHK', 'Dhaka'), ('CTG', 'Chattogram'), ('RJH', 'Rajshahi'), ('KHL', 'Khulna'), ('SYL', 'Sylhet'), ('BRS', 'Barisal'), ('RNG', 'Rangpur'), ('MYM', 'Mymensingh')], max_length=20, unique=True)),
                ('base_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_sla', models.CharField(blank=True, help_text="e.g. '1-2 days'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_override', models.BooleanField(default=False, help_text='If True, override_cost replaces all other shipping charges')),
                ('override_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rule', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Shipping Rule',
                'verbose_name_plural': 'Category Shipping Rules',
            },
        ),
        migrations.CreateModel(
            name='OrderValueShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_rules', to='orders.shippingzone')),
            ],
            options={
                'verbose_name': 'Order Value Shipping Rule',
                'verbose_name_plural': 'Order Value Shipping Rules',
                'ordering': ['min_order_value'],
            },
        ),
        migrations.CreateModel(
            name='LeftoverPackShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rule_type', models.CharField(choices=[('fixed', 'Fixed Cost'), ('reduced', 'Reduced (% off standard)'), ('free', 'Free Shipping'), ('zone_based', 'Zone-Based Cost')], max_length=20)),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reduction_percent', models.DecimalField(decimal_places=2, default=0, help_text="For 'reduced' type: % off standard shipping", max_digits=5)),
                ('zone_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, help_text='For zone_based type only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftover_rules', to='orders.shippingzone')),
            ],
            options={
                'verbose_name': 'Leftover Pack Shipping Rule',
                'verbose_name_plural': 'Leftover Pack Shipping Rules',
            },
        ),
        migrations.CreateModel(
            name='CourierProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('tracking_url', models.CharField(blank=True, help_text='Use {tracking_number} as placeholder', max_length=500)),
                ('webhook_url', models.CharField(blank=True, max_length=500)),
                ('base_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supported_zones', models.ManyToManyField(blank=True, related_name='couriers', to='orders.shippingzone')),
            ],
            options={
                'verbose_name': 'Courier Provider',
                'verbose_name_plural': 'Courier Providers',
            },
        ),
        migrations.CreateModel(
            name='ShippingZoneCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='orders.shippingzone')),
            ],
            options={
                'verbose_name': 'Zone Coverage',
                'verbose_name_plural': 'Zone Coverages',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('delivery_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('priority', models.SmallIntegerField(default=0, help_text='Lower = preferred')),
                ('is_active', models.BooleanField(default=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='orders.shippingzone')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeightShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_kg_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_rules', to='orders.shippingzone')),
            ],
            options={
                'verbose_name': 'Weight Shipping Rule',
                'verbose_name_plural': 'Weight Shipping Rules',
                'ordering': ['zone', 'min_weight'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseZoneMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_mappings', to='orders.warehouse')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_mappings', to='orders.shippingzone')),
            ],
            options={
                'verbose_name': 'Warehouse Zone Mapping',
                'unique_together': {('warehouse', 'zone')},
            },
        ),
    ]
