# Generated by Django 5.1.8 on 2026-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_leftover_pack_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='is_wholesale_only',
            field=models.BooleanField(default=False, help_text='If checked, this shipping method will only be available for wholesale orders'),
        ),
    ]
