# Generated by Django 5.1.8 on 2026-06-29 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_processed_at_store_order_processed_by'),
        ('wholesale', '0008_wholesalenotification_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processed_at_store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processed_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='wholesale_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_orders', to='wholesale.wholesaleuser'),
        ),
    ]
