# Generated by Django 5.1.8 on 2026-07-04 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_processed_at_store_and_more'),
        ('staff', '0011_staffshift_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, help_text='Staff member who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to='staff.staffprofile'),
        ),
    ]
