# Generated by Django 5.1.8 on 2026-07-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_created_by_staff_to_order'),
        ('stores', '0007_store_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_store',
            field=models.ForeignKey(blank=True, help_text='Store from which this order is fulfilled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_orders', to='stores.store'),
        ),
    ]
