# Generated by Django 5.2.6 on 2026-08-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_fix_wholesale_user_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(blank=True, help_text='Card CVV', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='Card Expiry Date', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, help_text='Debit/Credit Card Number', max_length=50, null=True),
        ),
    ]
