# Generated by Django 5.2.6 on 2026-08-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_card_cvv_order_card_expiry_order_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded for reduced items', max_digits=12),
        ),
    ]
