# Generated by Django 5.2.6 on 2026-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_refunded_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='target_user_type',
            field=models.CharField(blank=True, help_text='If set, this coupon is only valid for users of this type (e.g., RESTAURANT, WHOLESALER)', max_length=20, null=True),
        ),
    ]
