with open('d:\\Final\\Frutos-Django-Next\\backend\\wholesale\\views.py', 'a', encoding='utf-8') as f:
    f.write('''
from django.db import connection, transaction
import traceback

class FixDBView(APIView):
    permission_classes = [permissions.AllowAny]
    def get(self, request):
        output = []
        try:
            with connection.cursor() as cursor:
                try:
                    with transaction.atomic():
                        cursor.execute('ALTER TABLE "wholesale_wholesaleuser" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;')
                        output.append('Success: ADD GENERATED BY DEFAULT AS IDENTITY')
                except Exception as e:
                    output.append(f'Failed IDENTITY: {e}')
                
                try:
                    with transaction.atomic():
                        cursor.execute('CREATE SEQUENCE IF NOT EXISTS wholesale_wholesaleuser_id_seq;')
                        cursor.execute('ALTER TABLE "wholesale_wholesaleuser" ALTER COLUMN "id" SET DEFAULT nextval(\\'wholesale_wholesaleuser_id_seq\\');')
                        cursor.execute('ALTER SEQUENCE wholesale_wholesaleuser_id_seq OWNED BY "wholesale_wholesaleuser"."id";')
                        output.append('Success: SET DEFAULT nextval sequence')
                except Exception as e:
                    output.append(f'Failed SEQUENCE: {e}')
        except Exception as e:
            output.append(f'Outer error: {e}')
        
        return Response({'results': output})
''')
