# Generated by Django 5.1.8 on 2026-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_store_product_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, help_text='Product quality or variant (e.g., C, B)', max_length=100, null=True),
        ),
    ]
