# Generated by Django 5.1.8 on 2026-07-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_created_by_product_updated_by'),
        ('stores', '0007_store_store_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='stores.store')),
            ],
            options={
                'unique_together': {('product', 'store')},
            },
        ),
    ]
