# Generated by Django 5.1.8 on 2026-08-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., BANDEJA (TRAY)', max_length=255, unique=True)),
                ('abbreviation', models.CharField(blank=True, help_text='e.g., BAN', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
