# Generated by Django 5.2.6 on 2026-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_displayunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurant_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special discount price for restaurant orders', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special price for restaurant orders', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant_unit',
            field=models.CharField(blank=True, help_text='Restaurant unit (e.g., "per box")', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount price for wholesale orders', max_digits=10, null=True),
        ),
    ]
