# Generated by Django 5.1.8 on 2026-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_restaurant_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restaurant_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special discount price for external wholesale orders (Bahirer)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special price for external wholesale orders (Bahirer)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant_unit',
            field=models.CharField(blank=True, help_text='External Wholesale unit (e.g., "per box")', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount price for internal wholesale orders (Nijeder)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special price for internal wholesale orders (Nijeder) (leave empty if not applicable)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_unit',
            field=models.CharField(blank=True, help_text='Internal Wholesale unit (e.g., "per case")', max_length=200, null=True),
        ),
    ]
