# Generated by Django 5.1.8 on 2026-08-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_restaurant_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurant_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock available for External Wholesale (Bahirer)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock available for Internal Wholesale (Nijeder)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock available for Normal Customers'),
        ),
    ]
