# Generated by Django 5.1.8 on 2026-09-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_restaurant_stock_product_wholesale_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurant_minimum_purchase',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity required for external wholesale orders (Bahirer)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_purchase',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity required for internal wholesale orders (Nijeder)'),
        ),
    ]
