# Generated by Django 5.1.8 on 2026-06-22 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('stores', '0006_leftoverpack_shipping_category_leftoverpack_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='branch_location',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='stores.store'),
        ),
    ]
