# Generated by Django 5.1.8 on 2026-06-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staffprofile_branch_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='can_create_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_delete_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_update_orders',
            field=models.BooleanField(default=False),
        ),
    ]
