# Generated by Django 5.1.8 on 2026-06-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffprofile_can_create_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
