# Generated by Django 5.1.8 on 2026-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffprofile_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffshift',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
