# Generated by Django 5.1.8 on 2026-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffshift_break_end_staffshift_break_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
