# Generated by Django 5.1.8 on 2026-06-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staffprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='can_create_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_delete_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_update_products',
            field=models.BooleanField(default=False),
        ),
    ]
