# Generated by Django 5.2.6 on 2026-08-13 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_staffadminchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='announcement_files/'),
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='staff.announcement')),
            ],
        ),
    ]
