# Generated by Django 5.2.6 on 2026-08-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_announcement_attachment_file_announcementimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='attachment_file',
        ),
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcement_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='staff.announcement')),
            ],
        ),
    ]
