# Generated by Django 5.2.6 on 2026-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_announcement_attachment_file_announcementfile'),
        ('stores', '0010_store_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='restricted_stores',
            field=models.ManyToManyField(blank=True, related_name='restricted_staff', to='stores.store'),
        ),
    ]
