# Generated by Django 5.1.8 on 2026-06-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_offer_products_offeritem'),
        ('stores', '0005_leftoverpack_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftoverpack',
            name='shipping_category',
            field=models.ForeignKey(blank=True, help_text='Optional: Restrict to specific shipping methods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_category_leftover_packs', to='products.category'),
        ),
        migrations.AddField(
            model_name='leftoverpack',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg for weight-based shipping calculation', max_digits=10, null=True),
        ),
    ]
