# Generated by Django 5.2.6 on 2026-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='schedules',
            field=models.JSONField(blank=True, default=dict, help_text='Day-wise schedules (open, close, break_start, break_end)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Legacy closing time (use AM/PM picker)', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, help_text='Legacy opening time (use AM/PM picker)', null=True),
        ),
    ]
