# Generated by Django 5.2.6 on 2026-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_schedules_alter_store_close_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='schedules',
        ),
        migrations.AlterField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Closing time (use AM/PM picker)', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, help_text='Opening time (use AM/PM picker)', null=True),
        ),
    ]
