# Generated by Django 5.2.6 on 2026-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_store_schedules_alter_store_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='schedules',
            field=models.JSONField(blank=True, default=dict, help_text='Day-by-day schedules'),
        ),
    ]
