# Generated by Django 6.0.4 on 2026-05-06 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant / Bistro'), ('hotel', 'Hotel / Resort'), ('catering', 'Catering Company'), ('food_retail', 'Food Retail / Grocery'), ('dark_kitchen', 'Dark Kitchen'), ('cafe', 'Café / Bakery'), ('other', 'Other')], default='other', max_length=50)),
                ('monthly_volume', models.CharField(choices=[('400_1000', '€400 – €1,000 / month'), ('1000_3000', '€1,000 – €3,000 / month'), ('3000_7000', '€3,000 – €7,000 / month'), ('7000_plus', '€7,000+ / month')], default='400_1000', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('account_manager_name', models.CharField(blank=True, max_length=200)),
                ('account_manager_email', models.EmailField(blank=True, max_length=254)),
                ('admin_notes', models.TextField(blank=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('groups', models.ManyToManyField(blank=True, related_name='wholesale_users', related_query_name='wholesale_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='wholesale_users', related_query_name='wholesale_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Wholesale User',
                'verbose_name_plural': 'Wholesale Users',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application', 'Application Update'), ('order', 'Order Update'), ('pricing', 'Pricing Update'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wholesale.wholesaleuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='wholesale/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wholesale.wholesaleuser')),
            ],
        ),
    ]
