# Generated by Django 5.1.8 on 2026-06-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Card heading, e.g. 'Guaranteed Freshness'.", max_length=150)),
                ('body', models.TextField(help_text='1-3 sentence description displayed under the card title.')),
                ('icon_svg', models.TextField(help_text="Raw SVG markup for the icon inside the green rounded square.  Recommended size: 20×20.  Use stroke='#00694c' for the brand green.")),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first (left → right, top → bottom).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this benefit card without deleting it.')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Category heading, e.g. 'Fresh Vegetables'.", max_length=150)),
                ('items', models.TextField(help_text="Comma-separated example items shown in italic below the title.  e.g. 'Heirloom tomatoes, peppers, courgettes, aubergines, leafy greens'.")),
                ('badge', models.CharField(choices=[('Year-round', 'Year-round'), ('Seasonal', 'Seasonal'), ('Limited', 'Limited')], default='Year-round', help_text='Availability badge shown in the top-right corner of the card.', max_length=30)),
                ('badge_bg_color', models.CharField(default='#E7F1DF', help_text="Badge background colour as a CSS hex value, e.g. '#E7F1DF'.", max_length=20)),
                ('badge_text_color', models.CharField(default='#00694c', help_text="Badge text colour as a CSS hex value, e.g. '#00694c'.", max_length=20)),
                ('icon_svg', models.TextField(help_text='Raw SVG markup for the category icon.  Recommended size: 18×18.  Match the stroke colour to the icon background theme.')),
                ('icon_bg_color', models.CharField(default='#EDFAF2', help_text="Icon container background colour as a CSS hex value, e.g. '#EDFAF2'.", max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this category without deleting it.')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleGuaranteeBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No long-term commitment required', help_text='Bold title on the left side of the bar.', max_length=200)),
                ('subtitle', models.CharField(default='Rolling monthly arrangement. Upgrade or pause anytime.', help_text='Muted subtitle below the bar title.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guarantee Bar',
                'verbose_name_plural': 'Guarantee Bars',
            },
        ),
        migrations.CreateModel(
            name='WholesaleHeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Premium produce,', help_text="First line of the H1 heading, e.g. 'Premium produce,'", max_length=200)),
                ('headline_em', models.CharField(default='built for your business.', help_text="Second (italic / coloured) line of the H1, e.g. 'built for your business.'", max_length=200)),
                ('subtitle', models.TextField(default='El Árbol supplies restaurants, hotels, caterers, and retailers across Spain with directly sourced produce — harvested to order, delivered within 48 hours.', help_text='Paragraph beneath the headline (1-2 sentences).')),
                ('trust_text', models.CharField(default='Trusted by 200+ food businesses · Minimum order from €400/month', help_text='Small muted line below the subtitle, e.g. trust signals or minimum order info.', max_length=300)),
                ('hero_image', models.ImageField(help_text='Main hero image displayed on the right side of the section. Recommended: 1200×900px.', upload_to='wholesale/hero/')),
                ('badge_stat', models.CharField(default='48h', help_text="Large value shown in the top-right image badge, e.g. '48h'.", max_length=20)),
                ('badge_label', models.CharField(default='DELIVERY', help_text="Small label under the badge stat, e.g. 'DELIVERY'.", max_length=50)),
                ('bottom_badge_title', models.CharField(default='Harvested to order', help_text='Bold title in the bottom-left image overlay card.', max_length=100)),
                ('bottom_badge_subtitle', models.CharField(default='From 40+ certified farms across Spain', help_text='Muted subtitle in the bottom-left image overlay card.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only ONE hero should be active at a time. The first active row is served.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Content',
            },
        ),
        migrations.CreateModel(
            name='WholesaleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="The headline number or value, e.g. '200+', '48h', '99.1%'.", max_length=30)),
                ('label', models.CharField(help_text="Short descriptive label, e.g. 'Business Partners'.", max_length=100)),
                ('sub', models.CharField(help_text="Smaller subtext beneath the label, e.g. 'Restaurants, hotels & retailers'.", max_length=200)),
                ('icon_svg', models.TextField(help_text="Raw SVG markup for the stat icon.  Include the full <svg> element.  Tip: use stroke='currentColor' so the colour is controlled by CSS.")),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first (left → right).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Zero-padded step number string displayed above the title, e.g. '01', '02'.", max_length=5)),
                ('title', models.CharField(help_text="Step heading, e.g. 'Submit your application'.", max_length=150)),
                ('body', models.TextField(help_text='One short sentence describing what happens in this step.')),
                ('icon_svg', models.TextField(help_text="Raw SVG markup for the step icon.  Recommended size: 20×20.  Use stroke='currentColor' — the frontend will control colour based on whether the step is first.")),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — the step with order=0 gets the filled green circle style.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='wholesaleuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='wholesale/avatars/'),
        ),
        migrations.AddField(
            model_name='wholesaleuser',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleuser',
            name='trade_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        
        migrations.CreateModel(
            name='WholesaleGuaranteeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Short label shown next to the green tick, e.g. 'Cancel anytime'.", max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first (left → right).')),
                ('bar', models.ForeignKey(help_text='The guarantee bar these checks belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='wholesale.wholesaleguaranteebar')),
            ],
            options={
                'verbose_name': 'Guarantee Check Item',
                'verbose_name_plural': 'Guarantee Check Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Text shown inside the pill badge, e.g. 'Fine Dining'.", max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('hero', models.ForeignKey(help_text='Hero row these badges belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='trust_badges', to='wholesale.wholesaleherocontent')),
            ],
            options={
                'verbose_name': 'Trust Badge',
                'verbose_name_plural': 'Trust Badges',
                'ordering': ['order'],
            },
        ),
    ]
