# Generated by Django 5.1.8 on 2026-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_remove_wholesaleuser_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesalePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_section', models.JSONField(blank=True, default=dict, help_text='JSON for the hero section (badge, title_main, title_highlight, image_url, etc.)')),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero image displayed on the right side of the section. Recommended: 1200×900px.', null=True, upload_to='wholesale/hero/')),
                ('stats', models.JSONField(blank=True, default=list, help_text='Array of stat objects: [{ value, label, sub, icon_name }]')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Array of benefit objects: [{ title, body, icon_name }]')),
                ('categories', models.JSONField(blank=True, default=list, help_text='Array of category objects: [{ title, items, badge, badge_bg_color, badge_text_color, icon_name, icon_bg_color }]')),
                ('steps', models.JSONField(blank=True, default=list, help_text='Array of step objects: [{ number, title, body, icon_name }]')),
                ('guarantee', models.JSONField(blank=True, default=dict, help_text='JSON object for the guarantee bar: { title, subtitle, checks: [text, text...] }')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wholesale Page Content',
                'verbose_name_plural': 'Wholesale Page Content',
            },
        ),
        migrations.DeleteModel(
            name='WholesaleBenefit',
        ),
        migrations.DeleteModel(
            name='WholesaleCategory',
        ),
        migrations.RemoveField(
            model_name='wholesaleguaranteecheck',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='wholesaletrustbadge',
            name='hero',
        ),
        migrations.DeleteModel(
            name='WholesaleStat',
        ),
        migrations.DeleteModel(
            name='WholesaleStep',
        ),
        migrations.DeleteModel(
            name='WholesaleGuaranteeBar',
        ),
        migrations.DeleteModel(
            name='WholesaleGuaranteeCheck',
        ),
        migrations.DeleteModel(
            name='WholesaleHeroContent',
        ),
        migrations.DeleteModel(
            name='WholesaleTrustBadge',
        ),
    ]
