# Generated by Django 5.1.8 on 2026-06-10 08:20

import wholesale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_wholesalepagecontent_delete_wholesalebenefit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalepagecontent',
            name='benefits',
            field=models.JSONField(blank=True, default=wholesale.models.WholesalePageContent.default_benefits, help_text='Array of benefit objects: [{ title, body, icon_name }]'),
        ),
        migrations.AlterField(
            model_name='wholesalepagecontent',
            name='categories',
            field=models.JSONField(blank=True, default=wholesale.models.WholesalePageContent.default_categories, help_text='Array of category objects: [{ title, items, badge, badge_bg_color, badge_text_color, icon_name, icon_bg_color }]'),
        ),
        migrations.AlterField(
            model_name='wholesalepagecontent',
            name='guarantee',
            field=models.JSONField(blank=True, default=wholesale.models.WholesalePageContent.default_guarantee, help_text='JSON object for the guarantee bar: { title, subtitle, checks: [text, text...] }'),
        ),
        migrations.AlterField(
            model_name='wholesalepagecontent',
            name='hero_section',
            field=models.JSONField(blank=True, default=wholesale.models.WholesalePageContent.default_hero, help_text='JSON for the hero section (badge, title_main, title_highlight, image_url, etc.)'),
        ),
        migrations.AlterField(
            model_name='wholesalepagecontent',
            name='stats',
            field=models.JSONField(blank=True, default=wholesale.models.WholesalePageContent.default_stats, help_text='Array of stat objects: [{ value, label, sub, icon_name }]'),
        ),
        migrations.AlterField(
            model_name='wholesalepagecontent',
            name='steps',
            field=models.JSONField(blank=True, default=wholesale.models.WholesalePageContent.default_steps, help_text='Array of step objects: [{ number, title, body, icon_name }]'),
        ),
    ]
