# Generated by Django 5.1.8 on 2026-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wholesale', '0005_alter_wholesalepagecontent_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='wholesale_users_permissions', related_query_name='wholesale_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
