# Generated by Django 5.1.8 on 2026-07-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0008_wholesalenotification_metadata'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "wholesale_wholesaleuser" DROP COLUMN IF EXISTS "serial_number" CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        )
    ]
