# Generated by Django 5.1.8 on 2026-07-19 06:56

from django.db import migrations


def drop_serial_number_if_exists(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        try:
            if schema_editor.connection.vendor == 'postgresql':
                cursor.execute('ALTER TABLE "wholesale_wholesaleuser" DROP COLUMN IF EXISTS "serial_number" CASCADE;')
            elif schema_editor.connection.vendor == 'sqlite':
                # SQLite doesn't support DROP COLUMN IF EXISTS. Let's just try to drop it.
                cursor.execute('ALTER TABLE "wholesale_wholesaleuser" DROP COLUMN "serial_number";')
        except Exception:
            # Ignore if column doesn't exist
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0008_wholesalenotification_metadata'),
    ]

    operations = [
        migrations.RunPython(drop_serial_number_if_exists, reverse_code=migrations.RunPython.noop),
    ]
