# Generated by Django 5.1.8 on 2026-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0008_wholesalenotification_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
