# Generated by Django 5.1.8 on 2026-07-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0011_fix_id_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleuser',
            name='serial_number',
        ),
    ]
