# Generated by Django 5.1.8 on 2026-07-22 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0013_fix_wholesaleuser_id_sequence_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
