# Generated by Django 5.1.8 on 2026-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0013_fix_wholesaleuser_id_sequence_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleuser',
            name='user_type',
            field=models.CharField(choices=[('WHOLESALER', 'Internal Wholesale (Nijeder)'), ('RESTAURANT', 'External Wholesale (Bahirer)')], db_index=True, default='WHOLESALER', max_length=20),
        ),
    ]
