# Generated by Django 5.1.8 on 2026-08-25 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0014_wholesaleuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
