# Generated by Django 5.1.8 on 2026-06-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('WHOLESALER', 'Wholesaler'), ('VENDOR', 'Vendor'), ('AFFILIATE', 'Affiliate'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], db_index=True, default='CUSTOMER', max_length=12),
        ),
    ]
