# Generated by Django 5.2.6 on 2026-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_passwordresetotp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('WHOLESALER', 'Wholesaler'), ('RESTAURANT', 'Restaurant'), ('VENDOR', 'Vendor'), ('AFFILIATE', 'Affiliate'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], db_index=True, default='CUSTOMER', max_length=12),
        ),
    ]
