# Generated by Django 5.1.8 on 2026-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('WHOLESALER', 'Internal Wholesale (Nijeder)'), ('RESTAURANT', 'External Wholesale (Bahirer)'), ('VENDOR', 'Vendor'), ('AFFILIATE', 'Affiliate'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], db_index=True, default='CUSTOMER', max_length=12),
        ),
    ]
